// eslint-disable-next-line import/prefer-default-export
export function getLighthouseCalculatorUrl(report) {
  const measures = report.webVitals;
  if (report.lighthouseVersion.startsWith('6')) {
    return `https://googlechrome.github.io/lighthouse/scorecalc/#FCP=${measures.firstContentfulPaint.numericValue}&SI=${measures.speedIndex.numericValue}&LCP=${measures.largestContentfulPaint.numericValue}&TTI=${measures.interactive.numericValue}&TBT=${measures.totalBlockingTime.numericValue}&CLS=${measures.cumulativeLayoutShift.numericValue}&FCI=${measures.firstCpuIdle.numericValue}&FMP=${measures.firstMeaningfulPaint.numericValue}&FCI=${measures.firstCpuIdle.numericValue}&device=${report.configSettings.emulatedFormFactor}&version=6`;
    // return `https://googlechrome.github.io/lighthouse/scorecalc/#first-contentful-paint=${measures.firstContentfulPaint.numericValue}&speed-index=${measures.speedIndex.numericValue}&largest-contentful-paint=${measures.largestContentfulPaint.numericValue}&interactive=${measures.interactive.numericValue}&total-blocking-time=${measures.totalBlockingTime.numericValue}&cumulative-layout-shift=${measures.cumulativeLayoutShift.numericValue}&first-cpu-idle=${measures.firstCpuIdle.numericValue}&first-meaningful-paint=${measures.firstMeaningfulPaint.numericValue}&device=${report.configSettings.emulatedFormFactor}&version=6.0.0`;
  }

  return `https://googlechrome.github.io/lighthouse/scorecalc/#FCP=${measures.firstContentfulPaint.numericValue}&FMP=${measures.firstMeaningfulPaint.numericValue}&SI=${measures.speedIndex.numericValue}&TTI=${measures.interactive.numericValue}&FCI=${measures.firstCpuIdle.numericValue}&max-potential-fid=${measures.maxPotentialFid.numericValue}&FCI=${measures.firstCpuIdle.numericValue}&FMP=${measures.firstMeaningfulPaint.numericValue}&device=${report.configSettings.emulatedFormFactor}&version=5`;
  // return `https://googlechrome.github.io/lighthouse/scorecalc/#first-contentful-paint=${measures.firstContentfulPaint.numericValue}&first-meaningful-paint=${measures.firstMeaningfulPaint.numericValue}&speed-index=${measures.speedIndex.numericValue}&interactive=${measures.interactive.numericValue}&first-cpu-idle=${measures.firstCpuIdle.numericValue}&max-potential-fid=${measures.maxPotentialFid.numericValue}&first-cpu-idle=${measures.firstCpuIdle.numericValue}&first-meaningful-paint=${measures.firstMeaningfulPaint.numericValue}&device=${report.configSettings.emulatedFormFactor}&version=5.6.0`;
}
