name: Firebase Hosting CI/CD 
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run export
        env:
          SLICK_FIREBASE_API_KEY: ${{ secrets.SLICK_FIREBASE_API_KEY }}
          SLICK_FIREBASE_PROJECT_ID: ${{ secrets.SLICK_FIREBASE_PROJECT_ID }}
          SLICK_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.SLICK_FIREBASE_MESSAGING_SENDER_ID }}
          SLICK_FIREBASE_APP_ID: ${{ secrets.SLICK_FIREBASE_APP_ID }}
          SLICK_FIREBASE_AUTH_DOMAIN: ${{ secrets.SLICK_FIREBASE_AUTH_DOMAIN }}
          SLICK_API_BASE_URL: ${{ secrets.SLICK_API_BASE_URL }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: sapper_export
          path: __sapper__/export
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: sapper_export
          path: __sapper__/export
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
